import type { BillPayload, BillType, MoneyParts } from "./billing.types";

const esc = (value: unknown) => String(value ?? "—").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char);
const num = (value: unknown) => Number(value ?? 0).toLocaleString("en-NP", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const money = (value: unknown) => typeof value === "object" && value !== null && "display" in value ? esc((value as MoneyParts).display) : `Rs. ${num(value)}`;

const shippingLabel = (payload: BillPayload) => {
  const { sender, receiver, order, totals, company, bill } = payload;
  const logo = String(sender.logoUrl ?? company.logoUrl ?? "");
  return `<section class="print-page label"><header>${logo ? `<img src="${esc(logo)}" alt="Logo">` : `<strong>${esc(company.companyName)}</strong>`}<div><b>SENDER ADDRESS TO RECEIVER ADDRESS</b><small>${esc(bill.billNumber)}</small></div></header><main><div class="to"><small>TO</small><h1>${esc(receiver.name)}</h1><p><b>Phone:</b> ${esc(receiver.phone)} ${receiver.secondaryPhone ? `/ ${esc(receiver.secondaryPhone)}` : ""}</p><p><b>Address:</b> ${esc(receiver.address)}</p></div><aside><div><small>COD</small><strong>${Number(totals.codAmount ?? 0) > 0 ? money(totals.codAmount) : "PAID"}</strong></div><p><b>From:</b> ${esc(sender.name)}</p><p><b>Type:</b> ${esc(order.orderType ?? "Regular")}</p><p><b>Order ID:</b> ${esc(order.orderNumber)}</p></aside></main></section>`;
};

const vatBill = (payload: BillPayload) => {
  const vat = payload.vatInvoice;
  if (!vat) return `<section class="print-page invoice"><h1>VAT invoice data unavailable</h1></section>`;
  const { seller, buyer, invoice, rows, summary, signature } = vat;
  const logo = String(seller.logoUrl ?? "");
  return `<section class="print-page invoice"><header>${logo ? `<img src="${esc(logo)}" alt="Logo">` : ""}<div><h2>${esc(seller.displayName ?? seller.name)}</h2><p>${esc(seller.address)} · ${esc(seller.phone)}</p><p>PAN: ${esc(seller.panNumber)}</p></div><h1>${esc(vat.title)}</h1></header><div class="invoice-meta"><div><p><b>Invoice No:</b> ${esc(invoice.invoiceNumber)}</p><p><b>Buyer's Name:</b> ${esc(buyer.name)}</p><p><b>Address:</b> ${esc(buyer.address)}</p><p><b>Buyer PAN:</b> ${esc(buyer.panNumber)}</p></div><div><p><b>Transaction Date:</b> ${esc(invoice.transactionDate)}</p><p><b>Bill Issue Date:</b> ${esc(invoice.billIssueDate)}</p><p><b>Payment Mode:</b> ${esc(invoice.paymentMode)}</p><p><b>Order:</b> ${esc(invoice.orderNumber)}</p></div></div><table><thead><tr><th>S.N.</th><th>HS Code</th><th>Particulars</th><th>Qty</th><th>Rate</th><th>Amount</th><th>VAT</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${esc(row.serialNumber)}</td><td>${esc(row.hsCode ?? "")}</td><td>${esc(row.particulars)}</td><td>${esc(row.quantity)}</td><td>${money(row.rate)}</td><td>${money(row.amount)}</td><td>${money(row.vatAmount)}</td></tr>`).join("")}</tbody></table><div class="summary"><p>Sub-Total <b>${money(summary.subTotal)}</b></p><p>Discount <b>${money(summary.discount)}</b></p><p>Shipping <b>${money(summary.shipping)}</b></p><p>VAT (${esc(summary.vatPercent)}%) <b>${money(summary.vatAmount)}</b></p><p class="grand">Grand Total <b>${money(summary.grandTotal)}</b></p></div><p><b>In words:</b> ${esc(summary.inWords)}</p><footer><span>${esc(signature.receivedByLabel ?? "Received By")}</span><span>${esc(signature.sellerLabel ?? seller.name)}</span></footer></section>`;
};

const styles = `<style>@page{size:A4 portrait;margin:8mm}*{box-sizing:border-box}body{margin:0;color:#000;font-family:Arial,sans-serif}.print-page{break-after:page;page-break-after:always;overflow-wrap:anywhere}.print-page:last-child{break-after:auto;page-break-after:auto}.label{width:148mm;min-height:102mm;max-height:102mm;overflow:hidden;border:2px solid #000;padding:7mm}.label header{display:flex;align-items:center;justify-content:space-between;gap:5mm;border-bottom:2px solid #000;padding-bottom:5mm}.label header img,.invoice header img{max-width:35mm;max-height:18mm;object-fit:contain}.label header div{text-align:right}.label small{display:block;margin-top:3px}.label main{display:grid;grid-template-columns:minmax(0,2fr) minmax(44mm,1fr);min-height:70mm}.label .to{min-width:0;padding:6mm 5mm 4mm 0}.label .to h1{font-size:24px;line-height:1.1;margin:3mm 0}.label .to p,.label aside p{font-size:12px;line-height:1.35;margin:2mm 0}.label aside{border-left:2px solid #000;padding:5mm}.label aside>div{border:2px solid #000;text-align:center;padding:3mm;margin-bottom:4mm}.label aside strong{display:block;font-size:20px;margin-top:2mm}.invoice{width:190mm;min-height:270mm;padding:4mm}.invoice header{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:5mm;align-items:center;border-bottom:2px solid #000;padding-bottom:4mm}.invoice h1{font-size:22px}.invoice h2,.invoice p{margin:2mm 0}.invoice-meta{display:grid;grid-template-columns:1fr 1fr;gap:10mm;padding:4mm 0;font-size:12px}.invoice table{width:100%;border-collapse:collapse;table-layout:fixed}.invoice thead{display:table-header-group}.invoice tr{break-inside:avoid;page-break-inside:avoid}.invoice th,.invoice td{border:1px solid #000;padding:2mm;text-align:left;font-size:10px;overflow-wrap:anywhere}.invoice th:nth-child(1){width:8mm}.invoice th:nth-child(2){width:20mm}.invoice th:nth-child(4){width:10mm}.invoice th:nth-child(n+5){width:25mm}.summary{break-inside:avoid;margin:5mm 0 5mm auto;width:75mm}.summary p{display:flex;justify-content:space-between;border-bottom:1px solid #999;padding:1.5mm}.summary .grand{font-size:16px;border:2px solid #000;padding:3mm}.invoice footer{display:flex;justify-content:space-between;break-inside:avoid;margin-top:20mm;border-top:1px solid #000;padding-top:2mm}@media screen{body{background:#eee;padding:20px}.print-page{background:#fff;margin:0 auto 20px;box-shadow:0 2px 20px #999}}@media print{body{background:#fff;padding:0}.label{margin:0 auto}.invoice{width:100%;min-height:auto}}</style>`;

export const openBillPrintWindow = () => window.open("", "_blank", "width=1100,height=850");

export const printBills = async (payloads: ReadonlyArray<BillPayload>, billType: BillType, printWindow?: Window | null) => {
  const popup = printWindow ?? openBillPrintWindow();
  if (!popup) throw new Error("Pop-up blocked. Allow pop-ups to print bills.");
  const pages = payloads.map((payload) => billType === "VAT_BILL" ? vatBill(payload) : shippingLabel(payload)).join("");
  popup.document.open(); popup.document.write(`<!doctype html><html><head><title>${billType === "VAT_BILL" ? "VAT Bills" : "Shipping Labels"}</title>${styles}</head><body>${pages}<script>window.onload=()=>{setTimeout(()=>window.print(),250)}<\/script></body></html>`); popup.document.close();
};
