import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Gift, Loader2 } from "lucide-react";
import { useCreateLoyaltyTier, useLoyaltyTiers, useUpdateLoyaltyTier, type RewardType } from "@/features/loyalty";
import { ModernFormLayout, FormActions, FormField, FormSection } from "@/shared/components/forms/ModernFormLayout";
import { useToast } from "@/shared/components/feedback/ToastProvider";

type Form = { code: string; name: string; minYearlyPoints: string; maxYearlyPoints: string; sortOrder: string; isActive: boolean; freeDelivery: boolean; discountPercent: string; fixedAmountOff: string; rewardType: RewardType; rewardTitle: string; rewardDescription: string; benefitValue: string; expiresAt: string; hamperName: string; hamperSku: string; hamperItems: string };
const initial: Form = { code: "", name: "", minYearlyPoints: "0", maxYearlyPoints: "", sortOrder: "1", isActive: true, freeDelivery: false, discountPercent: "0", fixedAmountOff: "0", rewardType: "DIGITAL", rewardTitle: "", rewardDescription: "", benefitValue: "", expiresAt: "", hamperName: "", hamperSku: "", hamperItems: "" };
const input = "h-11 w-full rounded-xl border border-[#d2d2d7] bg-white px-3 text-sm outline-none focus:border-[var(--primary)]";
const normalizeCode = (value: string) => value.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");

export const LoyaltyTierFormPage: React.FC = () => {
  const { id } = useParams(); const navigate = useNavigate(); const toast = useToast(); const isEdit = Boolean(id); const tiers = useLoyaltyTiers(); const create = useCreateLoyaltyTier(); const update = useUpdateLoyaltyTier(); const [form, setForm] = React.useState<Form>(initial);
  React.useEffect(() => { if (!id) return; const row = tiers.data?.data.find((tier) => tier.id === id); if (!row) return; const reward = row.benefits?.reward; const hamper = reward?.benefitMeta?.giftHamper as Record<string, unknown> | undefined; setForm({ code: row.code, name: row.name, minYearlyPoints: String(row.minYearlyPoints), maxYearlyPoints: row.maxYearlyPoints == null ? "" : String(row.maxYearlyPoints), sortOrder: String(row.sortOrder ?? 1), isActive: row.isActive, freeDelivery: Boolean(row.benefits?.freeDelivery), discountPercent: String(row.benefits?.discountPercent ?? row.benefits?.percentOff ?? 0), fixedAmountOff: String(row.benefits?.fixedAmountOff ?? row.benefits?.amountOff ?? 0), rewardType: reward?.rewardType ?? reward?.type ?? "DIGITAL", rewardTitle: reward?.title ?? "", rewardDescription: reward?.description ?? "", benefitValue: reward?.benefitValue == null ? "" : String(reward.benefitValue), expiresAt: reward?.expiresAt?.slice(0, 16) ?? "", hamperName: typeof hamper?.name === "string" ? hamper.name : "", hamperSku: typeof hamper?.sku === "string" ? hamper.sku : "", hamperItems: Array.isArray(hamper?.items) ? (hamper.items as Array<Record<string, unknown>>).map((item) => `${item.name ?? ""}:${item.quantity ?? 1}`).join("\n") : "" }); }, [id, tiers.data?.data]);
  const set = <K extends keyof Form>(key: K, value: Form[K]) => setForm((prev) => ({ ...prev, [key]: value }));
  const save: React.FormEventHandler = async (event) => { event.preventDefault(); const min = Number(form.minYearlyPoints); const max = form.maxYearlyPoints ? Number(form.maxYearlyPoints) : null; const code = normalizeCode(form.code); const existing = tiers.data?.data.filter((tier) => tier.id !== id) ?? []; if (!form.name.trim() || !code) return toast.error("Tier name and code are required."); if (min < 0 || (max != null && max < min)) return toast.error("Tier point range is invalid."); if (existing.some((tier) => normalizeCode(tier.code) === code)) return toast.error("A tier with this code already exists."); if (existing.some((tier) => tier.sortOrder === Number(form.sortOrder))) return toast.error("Another tier already uses this sort order."); if (max == null && existing.some((tier) => tier.maxYearlyPoints == null)) return toast.error("Only one tier can have an open-ended maximum."); const overlap = existing.find((tier) => { const otherMax = tier.maxYearlyPoints ?? Number.POSITIVE_INFINITY; const currentMax = max ?? Number.POSITIVE_INFINITY; return min <= otherMax && tier.minYearlyPoints <= currentMax; }); if (overlap) return toast.error(`Point range overlaps with ${overlap.name}.`); const discount = Number(form.discountPercent) || 0; const fixed = Number(form.fixedAmountOff) || 0; if (discount < 0 || discount > 100 || fixed < 0) return toast.error("Benefit values are invalid."); const parsedLines = form.hamperItems.split("\n").filter((line) => line.trim()); const items = parsedLines.map((line) => { const [name, quantity] = line.split(":"); return { name: name?.trim(), quantity: Number(quantity) }; }); if (form.rewardType === "PHYSICAL" && (!form.hamperName.trim() || !form.hamperSku.trim() || items.some((item) => !item.name || !Number.isInteger(item.quantity) || item.quantity <= 0))) return toast.error("Physical rewards require a hamper name, SKU, and valid item quantities."); const dto = { code: form.code, name: form.name.trim(), minYearlyPoints: min, maxYearlyPoints: max, sortOrder: Number(form.sortOrder) || 1, isActive: form.isActive, benefits: { freeDelivery: form.freeDelivery, discountPercent: discount, fixedAmountOff: fixed, reward: { rewardType: form.rewardType, title: form.rewardTitle.trim() || `${form.name} Reward`, description: form.rewardDescription.trim() || null, benefitValue: form.benefitValue || null, expiresAt: form.expiresAt ? new Date(form.expiresAt).toISOString() : null, benefitMeta: form.rewardType === "PHYSICAL" ? { giftHamper: { name: form.hamperName, sku: form.hamperSku, items } } : null } } }; if (id) await update.mutateAsync({ id, dto }); else await create.mutateAsync(dto); navigate("/dashboard/loyalty/tiers"); };
  const saving = create.isPending || update.isPending;
  return <ModernFormLayout title={isEdit ? "Edit Loyalty Tier" : "Create Loyalty Tier"} subtitle="Configure yearly thresholds, customer benefits, and generated rewards." onBack={() => navigate("/dashboard/loyalty/tiers")}><form onSubmit={save} className="space-y-6"><FormSection title="Tier identity"><div className="grid gap-4 md:grid-cols-2"><FormField label="Display name" required><input value={form.name} onChange={(e) => set("name", e.target.value)} className={input} /></FormField><FormField label="Code" required hint={`Normalized: ${normalizeCode(form.code) || "—"}`}><input value={form.code} onChange={(e) => set("code", e.target.value)} className={input} /></FormField><FormField label="Minimum yearly points" required><input type="number" min="0" value={form.minYearlyPoints} onChange={(e) => set("minYearlyPoints", e.target.value)} className={input} /></FormField><FormField label="Maximum yearly points"><input type="number" min="0" value={form.maxYearlyPoints} onChange={(e) => set("maxYearlyPoints", e.target.value)} className={input} /></FormField><FormField label="Sort order"><input type="number" value={form.sortOrder} onChange={(e) => set("sortOrder", e.target.value)} className={input} /></FormField><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => set("isActive", e.target.checked)} />Active tier</label></div></FormSection>
    <FormSection title="Benefits"><div className="grid gap-4 md:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.freeDelivery} onChange={(e) => set("freeDelivery", e.target.checked)} />Free delivery</label><FormField label="Discount percent"><input type="number" min="0" max="100" value={form.discountPercent} onChange={(e) => set("discountPercent", e.target.value)} className={input} /></FormField><FormField label="Fixed amount off"><input type="number" min="0" value={form.fixedAmountOff} onChange={(e) => set("fixedAmountOff", e.target.value)} className={input} /></FormField></div></FormSection>
    <FormSection title="Tier reward" description="Generated automatically when a customer enters this tier. Digital rewards start assigned; physical rewards start pending."><div className="grid gap-4 md:grid-cols-2"><FormField label="Reward type"><select value={form.rewardType} onChange={(e) => set("rewardType", e.target.value as RewardType)} className={input}><option value="DIGITAL">Digital</option><option value="PHYSICAL">Physical</option></select></FormField><FormField label="Reward title"><input value={form.rewardTitle} onChange={(e) => set("rewardTitle", e.target.value)} className={input} /></FormField><FormField label="Benefit value"><input value={form.benefitValue} onChange={(e) => set("benefitValue", e.target.value)} className={input} /></FormField><FormField label="Expires at"><input type="datetime-local" value={form.expiresAt} onChange={(e) => set("expiresAt", e.target.value)} className={input} /></FormField><FormField label="Description"><textarea value={form.rewardDescription} onChange={(e) => set("rewardDescription", e.target.value)} className="min-h-24 w-full rounded-xl border p-3" /></FormField></div>{form.rewardType === "PHYSICAL" ? <div className="mt-4 grid gap-4 md:grid-cols-2"><FormField label="Hamper name"><input value={form.hamperName} onChange={(e) => set("hamperName", e.target.value)} className={input} /></FormField><FormField label="Hamper SKU"><input value={form.hamperSku} onChange={(e) => set("hamperSku", e.target.value)} className={input} /></FormField><FormField label="Hamper items" hint="One per line: Item name:quantity"><textarea value={form.hamperItems} onChange={(e) => set("hamperItems", e.target.value)} className="min-h-28 w-full rounded-xl border p-3" /></FormField><div className="flex items-center justify-center rounded-xl bg-amber-50 text-amber-800"><Gift className="mr-2" />Physical fulfillment remains manual.</div></div> : null}</FormSection>
    <FormActions submitLabel={saving ? "Saving..." : isEdit ? "Update Tier" : "Create Tier"} submitIcon={saving ? <Loader2 className="animate-spin" size={14} /> : undefined} isSubmitting={saving} onCancel={() => navigate("/dashboard/loyalty/tiers")} /></form></ModernFormLayout>;
};
