import React from "react";
import { Gift, PackageCheck, UserCheck } from "lucide-react";
import { useFulfillLoyaltyReward, useLoyaltyRewards, type LoyaltyReward, type RewardStatus } from "@/features/loyalty";
import { PageLayout } from "@/shared/components/dashboard/PageLayout";
import { StatCardV2 } from "@/shared/components/dashboard/StatCardV2";
import { DataTableV2 } from "@/shared/components/dashboard/DataTableV2";
import { useListQueryState } from "@/shared/hooks/useListQueryState";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/shared/components/ui/alert-dialog";
import { RewardBadge, TierBadge, customerName, date, text } from "./loyaltyUi";
import { AdminUserSearchPicker } from "@/shared/components/forms/AdminUserSearchPicker";
import type { AdminUserSearchOption } from "@/shared/hooks/useAdminUserSearch";
import { ExportMenu } from "@/shared/components/dashboard/ExportMenu";

export const LoyaltyRewardsPage: React.FC = () => {
  const { state, setState, debouncedSearch } = useListQueryState({ page: 1, limit: 20, search: "" }); const query = useLoyaltyRewards({ page: state.page, limit: state.limit, search: debouncedSearch || undefined }); const fulfill = useFulfillLoyaltyReward();
  const [selected, setSelected] = React.useState<LoyaltyReward | null>(null); const [status, setStatus] = React.useState<RewardStatus>("FULFILLED"); const [staff, setStaff] = React.useState<AdminUserSearchOption | null>(null); const [note, setNote] = React.useState(""); const rows = query.data?.data ?? [];
  const columns = [{ key: "customer", label: "Customer", render: (row: LoyaltyReward) => customerName(row.customer) },{ key: "title", label: "Reward", render: (row: LoyaltyReward) => <div><p className="font-semibold">{row.title}</p><p className="text-xs text-gray-500">{text(row.description)}</p></div> },{ key: "tierCode", label: "Tier", render: (row: LoyaltyReward) => <TierBadge code={row.tierCode} /> },{ key: "rewardType", label: "Type", render: (row: LoyaltyReward) => row.rewardType },{ key: "rewardStatus", label: "Status", render: (row: LoyaltyReward) => <RewardBadge status={row.rewardStatus} /> },{ key: "expiresAt", label: "Expires", render: (row: LoyaltyReward) => date(row.expiresAt) }];
  const save = async () => { if (!selected) return; await fulfill.mutateAsync({ id: selected.id, dto: { rewardStatus: status, assignedToStaffId: staff?.id, fulfilledAt: status === "FULFILLED" ? new Date().toISOString() : undefined, metadata: note.trim() ? { fulfillmentNote: note.trim() } : undefined } }); setSelected(null); setStaff(null); };
  return <PageLayout title="Loyalty Rewards" subtitle="Assign and fulfill generated digital and physical tier rewards." searchValue={state.search} onSearchChange={(search) => setState((prev) => ({ ...prev, page: 1, search }))} searchPlaceholder="Search rewards..."><div className="grid gap-4 sm:grid-cols-3"><StatCardV2 label="Total Rewards" value={query.data?.total ?? rows.length} icon={Gift} colorVariant="blue" /><StatCardV2 label="Pending" value={rows.filter((row) => row.rewardStatus === "PENDING").length} icon={UserCheck} colorVariant="amber" /><StatCardV2 label="Physical on Page" value={rows.filter((row) => row.rewardType === "PHYSICAL").length} icon={PackageCheck} colorVariant="emerald" /></div><DataTableV2 columns={columns} data={rows} onRowClick={(row) => { setSelected(row); setStatus(row.rewardStatus === "PENDING" ? "ASSIGNED" : "FULFILLED"); }} emptyMessage={query.isLoading ? "Loading rewards..." : "No loyalty rewards found."} showPagination currentPage={state.page} totalPages={query.data?.totalPages ?? 1} onPageChange={(page) => setState((prev) => ({ ...prev, page }))} />
    <AlertDialog open={Boolean(selected)} onOpenChange={(open) => { if (!open) { setSelected(null); setStaff(null); } }}><AlertDialogContent className="bg-white"><AlertDialogHeader><AlertDialogTitle>Update reward</AlertDialogTitle><AlertDialogDescription>Assign or fulfill {selected?.title}. Physical shipment attachment remains a manual process.</AlertDialogDescription></AlertDialogHeader><div className="space-y-4"><label className="block text-sm font-medium">Status<select value={status} onChange={(e) => setStatus(e.target.value as RewardStatus)} className="mt-1 h-11 w-full rounded-lg border px-3"><option>PENDING</option><option>ASSIGNED</option><option>FULFILLED</option><option>REDEEMED</option><option>EXPIRED</option></select></label><AdminUserSearchPicker label="Assigned staff" value={staff} onChange={setStaff} required={status === "ASSIGNED" || status === "FULFILLED"} helperText="Search and select the staff member responsible for this reward." /><label className="block text-sm font-medium">Fulfillment note<textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3" /></label></div><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={fulfill.isPending || ((status === "ASSIGNED" || status === "FULFILLED") && !staff)} onClick={(event) => { event.preventDefault(); void save(); }}>Save reward</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <div className="flex justify-end"><ExportMenu basePath="/customer-loyalty/admin/rewards" params={{ search: debouncedSearch || undefined, limit: 10000 }} filename="loyalty-rewards"/></div>
  </PageLayout>;
};
