import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Award, Coins, Gift, TrendingUp } from "lucide-react";
import { useAdjustLoyaltyPoints, useLoyaltyCustomer } from "@/features/loyalty";
import { PageLayout } from "@/shared/components/dashboard/PageLayout";
import { StatCardV2 } from "@/shared/components/dashboard/StatCardV2";
import { DataTableV2 } from "@/shared/components/dashboard/DataTableV2";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/shared/components/ui/alert-dialog";
import { RewardBadge, TierBadge, customerName, date, number, text } from "./loyaltyUi";

const rowsFrom = (value: unknown, keys: string[]) => { const row = typeof value === "object" && value !== null ? value as Record<string, unknown> : {}; for (const key of keys) if (Array.isArray(row[key])) return row[key] as Record<string, unknown>[]; return []; };

export const LoyaltyCustomerDetailPage: React.FC = () => {
  const { customerId } = useParams(); const navigate = useNavigate();
  const query = useLoyaltyCustomer(customerId); const adjust = useAdjustLoyaltyPoints();
  const [open, setOpen] = React.useState(false); const [points, setPoints] = React.useState("100"); const [reason, setReason] = React.useState("");
  const data = query.data ?? {}; const profile = (data.profile ?? data.loyaltyProfile ?? data) as Record<string, unknown>; const customer = data.customer ?? profile.customer ?? data;
  const ledgers = rowsFrom(data, ["ledgers", "pointLedgers", "points"]); const rewards = rowsFrom(data, ["rewards", "loyaltyRewards"]); const referrals = rowsFrom(data, ["referrals", "customerReferrals"]);
  const submit = async () => { const parsed = Number(points); if (!customerId || !Number.isFinite(parsed) || parsed === 0 || !reason.trim()) return; await adjust.mutateAsync({ customerId, dto: { points: parsed, reason: reason.trim(), sourceType: "ADMIN_BONUS" } }); setOpen(false); setReason(""); };
  return <PageLayout title={customerName(customer)} subtitle="Customer loyalty profile, point history, rewards, and referrals." onBack={() => navigate("/dashboard/loyalty/leaderboard")} actions={<button type="button" onClick={() => setOpen(true)} className="rounded-full bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white">Adjust Points</button>}>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCardV2 label="Rank" value={number(data.rank ?? profile.rank) > 0 ? `#${number(data.rank ?? profile.rank)}` : "—"} icon={TrendingUp} colorVariant="blue" /><StatCardV2 label="Yearly Points" value={number(profile.yearlyPoints).toLocaleString()} icon={Coins} colorVariant="emerald" /><StatCardV2 label="Lifetime Points" value={number(profile.lifetimePoints).toLocaleString()} icon={Award} colorVariant="cyan" /><StatCardV2 label="Rewards" value={rewards.length} icon={Gift} colorVariant="amber" /></div>
    <div className="rounded-2xl border border-[#e5e5ea] bg-white p-5"><div className="grid gap-4 md:grid-cols-4"><div><p className="text-xs text-gray-500">Current tier</p><div className="mt-2"><TierBadge code={text(profile.currentTierCode, "UNASSIGNED")} /></div></div><div><p className="text-xs text-gray-500">Referral code</p><p className="mt-2 font-mono font-semibold">{text(profile.referralCode)}</p></div><div><p className="text-xs text-gray-500">Last evaluated</p><p className="mt-2 text-sm">{date(profile.lastTierEvaluatedAt)}</p></div><div><p className="text-xs text-gray-500">Year reset</p><p className="mt-2 text-sm">{date(profile.yearlyResetAt)}</p></div></div></div>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Point Ledger</h2><DataTableV2 columns={[{ key: "points", label: "Points", render: (row: Record<string, unknown>) => <span className={`font-bold ${number(row.points) >= 0 ? "text-emerald-700" : "text-red-700"}`}>{number(row.points) > 0 ? "+" : ""}{number(row.points)}</span> },{ key: "sourceType", label: "Source", render: (row: Record<string, unknown>) => text(row.sourceType) },{ key: "reason", label: "Reason", render: (row: Record<string, unknown>) => text(row.reason) },{ key: "yearBucket", label: "Year", render: (row: Record<string, unknown>) => text(row.yearBucket) },{ key: "createdAt", label: "Date", render: (row: Record<string, unknown>) => date(row.createdAt) }]} data={ledgers} emptyMessage={query.isLoading ? "Loading loyalty profile..." : "No point ledger entries."} /></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Rewards</h2><DataTableV2 columns={[{ key: "title", label: "Reward", render: (row: Record<string, unknown>) => text(row.title) },{ key: "tierCode", label: "Tier", render: (row: Record<string, unknown>) => <TierBadge code={text(row.tierCode, "")} /> },{ key: "rewardType", label: "Type", render: (row: Record<string, unknown>) => text(row.rewardType) },{ key: "rewardStatus", label: "Status", render: (row: Record<string, unknown>) => <RewardBadge status={text(row.rewardStatus, "PENDING")} /> },{ key: "fulfilledAt", label: "Fulfilled", render: (row: Record<string, unknown>) => date(row.fulfilledAt) }]} data={rewards} emptyMessage="No rewards generated." /></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Referrals</h2><DataTableV2 columns={[{ key: "referralCode", label: "Code", render: (row: Record<string, unknown>) => text(row.referralCode) },{ key: "status", label: "Status", render: (row: Record<string, unknown>) => text(row.status) },{ key: "qualifiedAt", label: "Qualified", render: (row: Record<string, unknown>) => date(row.qualifiedAt) },{ key: "rewardedAt", label: "Rewarded", render: (row: Record<string, unknown>) => date(row.rewardedAt) }]} data={referrals} emptyMessage="No referral history." /></section>
    <AlertDialog open={open} onOpenChange={setOpen}><AlertDialogContent className="bg-white"><AlertDialogHeader><AlertDialogTitle>Adjust loyalty points</AlertDialogTitle><AlertDialogDescription>Use a positive value to award points or a negative value to correct points. A reason is required.</AlertDialogDescription></AlertDialogHeader><div className="space-y-4"><label className="block text-sm font-medium">Points<input type="number" value={points} onChange={(event) => setPoints(event.target.value)} className="mt-1 h-11 w-full rounded-lg border px-3" /></label><label className="block text-sm font-medium">Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3" /></label></div><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={adjust.isPending || Number(points) === 0 || !reason.trim()} onClick={(event) => { event.preventDefault(); void submit(); }}>Confirm adjustment</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </PageLayout>;
};
